/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as NewsRouteImport } from './routes/news'
import { Route as LoginRouteImport } from './routes/login'
import { Route as InsightsRouteImport } from './routes/insights'
import { Route as BookRouteImport } from './routes/book'
import { Route as AppRouteImport } from './routes/app'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ServicesIndexRouteImport } from './routes/services.index'
import { Route as NewsIndexRouteImport } from './routes/news.index'
import { Route as ServicesServiceIdRouteImport } from './routes/services.$serviceId'
import { Route as NewsIdRouteImport } from './routes/news.$id'
import { Route as DashboardProviderRouteImport } from './routes/dashboard.provider'
import { Route as DashboardHomeownerRouteImport } from './routes/dashboard.homeowner'
import { Route as DashboardAdminRouteImport } from './routes/dashboard.admin'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as UsernameBookRouteImport } from './routes/$username.book'
import { Route as ServicesServiceIdIndexRouteImport } from './routes/services.$serviceId.index'
import { Route as ServicesServiceIdSubServiceIdRouteImport } from './routes/services.$serviceId.$subServiceId'
import { Route as AuthenticatedUsernameWalletRouteImport } from './routes/_authenticated.$username.wallet'
import { Route as AuthenticatedUsernameUpdateNewsRouteImport } from './routes/_authenticated.$username.update-news'
import { Route as AuthenticatedUsernameSystemHealthRouteImport } from './routes/_authenticated.$username.system-health'
import { Route as AuthenticatedUsernameSecurityRouteImport } from './routes/_authenticated.$username.security'
import { Route as AuthenticatedUsernameReviewsRouteImport } from './routes/_authenticated.$username.reviews'
import { Route as AuthenticatedUsernameProvidersRouteImport } from './routes/_authenticated.$username.providers'
import { Route as AuthenticatedUsernameProfileRouteImport } from './routes/_authenticated.$username.profile'
import { Route as AuthenticatedUsernamePastBookingsRouteImport } from './routes/_authenticated.$username.past-bookings'
import { Route as AuthenticatedUsernameOverviewRouteImport } from './routes/_authenticated.$username.overview'
import { Route as AuthenticatedUsernameNotificationRouteImport } from './routes/_authenticated.$username.notification'
import { Route as AuthenticatedUsernameNewJobsRouteImport } from './routes/_authenticated.$username.new-jobs'
import { Route as AuthenticatedUsernameMyservicesRouteImport } from './routes/_authenticated.$username.myservices'
import { Route as AuthenticatedUsernameJobsBookingsRouteImport } from './routes/_authenticated.$username.jobs-bookings'
import { Route as AuthenticatedUsernameJobsRouteImport } from './routes/_authenticated.$username.jobs'
import { Route as AuthenticatedUsernameHomeownersRouteImport } from './routes/_authenticated.$username.homeowners'
import { Route as AuthenticatedUsernameDashboardRouteImport } from './routes/_authenticated.$username.dashboard'
import { Route as AuthenticatedUsernameActiveBookingsRouteImport } from './routes/_authenticated.$username.active-bookings'
import { Route as AuthenticatedUsernameUpdateNewsIndexRouteImport } from './routes/_authenticated.$username.update-news.index'
import { Route as AuthenticatedUsernameProvidersIndexRouteImport } from './routes/_authenticated.$username.providers.index'
import { Route as AuthenticatedUsernameProviderRequestIndexRouteImport } from './routes/_authenticated.$username.provider-request.index'
import { Route as AuthenticatedUsernameMyservicesIndexRouteImport } from './routes/_authenticated.$username.myservices.index'
import { Route as AuthenticatedUsernameHomeownersIndexRouteImport } from './routes/_authenticated.$username.homeowners.index'
import { Route as AuthenticatedUsernameCategoryRequestIndexRouteImport } from './routes/_authenticated.$username.category-request.index'
import { Route as AuthenticatedUsernameUpdateNewsNewRouteImport } from './routes/_authenticated.$username.update-news.new'
import { Route as AuthenticatedUsernameProvidersIdRouteImport } from './routes/_authenticated.$username.providers.$id'
import { Route as AuthenticatedUsernameProviderRequestIdRouteImport } from './routes/_authenticated.$username.provider-request.$id'
import { Route as AuthenticatedUsernameMyservicesNewRouteImport } from './routes/_authenticated.$username.myservices.new'
import { Route as AuthenticatedUsernameMyservicesCardIdRouteImport } from './routes/_authenticated.$username.myservices.$cardId'
import { Route as AuthenticatedUsernameHomeownersIdRouteImport } from './routes/_authenticated.$username.homeowners.$id'
import { Route as AuthenticatedUsernameCategoryRequestIdRouteImport } from './routes/_authenticated.$username.category-request.$id'
import { Route as AuthenticatedUsernameUpdateNewsIdEditRouteImport } from './routes/_authenticated.$username.update-news.$id.edit'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsRoute = NewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const InsightsRoute = InsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => rootRouteImport,
} as any)
const BookRoute = BookRouteImport.update({
  id: '/book',
  path: '/book',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesIndexRoute = ServicesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ServicesRoute,
} as any)
const NewsIndexRoute = NewsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => NewsRoute,
} as any)
const ServicesServiceIdRoute = ServicesServiceIdRouteImport.update({
  id: '/$serviceId',
  path: '/$serviceId',
  getParentRoute: () => ServicesRoute,
} as any)
const NewsIdRoute = NewsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => NewsRoute,
} as any)
const DashboardProviderRoute = DashboardProviderRouteImport.update({
  id: '/dashboard/provider',
  path: '/dashboard/provider',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardHomeownerRoute = DashboardHomeownerRouteImport.update({
  id: '/dashboard/homeowner',
  path: '/dashboard/homeowner',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardAdminRoute = DashboardAdminRouteImport.update({
  id: '/dashboard/admin',
  path: '/dashboard/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const UsernameBookRoute = UsernameBookRouteImport.update({
  id: '/$username/book',
  path: '/$username/book',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesServiceIdIndexRoute = ServicesServiceIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ServicesServiceIdRoute,
} as any)
const ServicesServiceIdSubServiceIdRoute =
  ServicesServiceIdSubServiceIdRouteImport.update({
    id: '/$subServiceId',
    path: '/$subServiceId',
    getParentRoute: () => ServicesServiceIdRoute,
  } as any)
const AuthenticatedUsernameWalletRoute =
  AuthenticatedUsernameWalletRouteImport.update({
    id: '/$username/wallet',
    path: '/$username/wallet',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedUsernameUpdateNewsRoute =
  AuthenticatedUsernameUpdateNewsRouteImport.update({
    id: '/$username/update-news',
    path: '/$username/update-news',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedUsernameSystemHealthRoute =
  AuthenticatedUsernameSystemHealthRouteImport.update({
    id: '/$username/system-health',
    path: '/$username/system-health',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedUsernameSecurityRoute =
  AuthenticatedUsernameSecurityRouteImport.update({
    id: '/$username/security',
    path: '/$username/security',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedUsernameReviewsRoute =
  AuthenticatedUsernameReviewsRouteImport.update({
    id: '/$username/reviews',
    path: '/$username/reviews',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedUsernameProvidersRoute =
  AuthenticatedUsernameProvidersRouteImport.update({
    id: '/$username/providers',
    path: '/$username/providers',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedUsernameProfileRoute =
  AuthenticatedUsernameProfileRouteImport.update({
    id: '/$username/profile',
    path: '/$username/profile',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedUsernamePastBookingsRoute =
  AuthenticatedUsernamePastBookingsRouteImport.update({
    id: '/$username/past-bookings',
    path: '/$username/past-bookings',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedUsernameOverviewRoute =
  AuthenticatedUsernameOverviewRouteImport.update({
    id: '/$username/overview',
    path: '/$username/overview',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedUsernameNotificationRoute =
  AuthenticatedUsernameNotificationRouteImport.update({
    id: '/$username/notification',
    path: '/$username/notification',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedUsernameNewJobsRoute =
  AuthenticatedUsernameNewJobsRouteImport.update({
    id: '/$username/new-jobs',
    path: '/$username/new-jobs',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedUsernameMyservicesRoute =
  AuthenticatedUsernameMyservicesRouteImport.update({
    id: '/$username/myservices',
    path: '/$username/myservices',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedUsernameJobsBookingsRoute =
  AuthenticatedUsernameJobsBookingsRouteImport.update({
    id: '/$username/jobs-bookings',
    path: '/$username/jobs-bookings',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedUsernameJobsRoute =
  AuthenticatedUsernameJobsRouteImport.update({
    id: '/$username/jobs',
    path: '/$username/jobs',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedUsernameHomeownersRoute =
  AuthenticatedUsernameHomeownersRouteImport.update({
    id: '/$username/homeowners',
    path: '/$username/homeowners',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedUsernameDashboardRoute =
  AuthenticatedUsernameDashboardRouteImport.update({
    id: '/$username/dashboard',
    path: '/$username/dashboard',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedUsernameActiveBookingsRoute =
  AuthenticatedUsernameActiveBookingsRouteImport.update({
    id: '/$username/active-bookings',
    path: '/$username/active-bookings',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedUsernameUpdateNewsIndexRoute =
  AuthenticatedUsernameUpdateNewsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedUsernameUpdateNewsRoute,
  } as any)
const AuthenticatedUsernameProvidersIndexRoute =
  AuthenticatedUsernameProvidersIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedUsernameProvidersRoute,
  } as any)
const AuthenticatedUsernameProviderRequestIndexRoute =
  AuthenticatedUsernameProviderRequestIndexRouteImport.update({
    id: '/$username/provider-request/',
    path: '/$username/provider-request/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedUsernameMyservicesIndexRoute =
  AuthenticatedUsernameMyservicesIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedUsernameMyservicesRoute,
  } as any)
const AuthenticatedUsernameHomeownersIndexRoute =
  AuthenticatedUsernameHomeownersIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedUsernameHomeownersRoute,
  } as any)
const AuthenticatedUsernameCategoryRequestIndexRoute =
  AuthenticatedUsernameCategoryRequestIndexRouteImport.update({
    id: '/$username/category-request/',
    path: '/$username/category-request/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedUsernameUpdateNewsNewRoute =
  AuthenticatedUsernameUpdateNewsNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => AuthenticatedUsernameUpdateNewsRoute,
  } as any)
const AuthenticatedUsernameProvidersIdRoute =
  AuthenticatedUsernameProvidersIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedUsernameProvidersRoute,
  } as any)
const AuthenticatedUsernameProviderRequestIdRoute =
  AuthenticatedUsernameProviderRequestIdRouteImport.update({
    id: '/$username/provider-request/$id',
    path: '/$username/provider-request/$id',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedUsernameMyservicesNewRoute =
  AuthenticatedUsernameMyservicesNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => AuthenticatedUsernameMyservicesRoute,
  } as any)
const AuthenticatedUsernameMyservicesCardIdRoute =
  AuthenticatedUsernameMyservicesCardIdRouteImport.update({
    id: '/$cardId',
    path: '/$cardId',
    getParentRoute: () => AuthenticatedUsernameMyservicesRoute,
  } as any)
const AuthenticatedUsernameHomeownersIdRoute =
  AuthenticatedUsernameHomeownersIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedUsernameHomeownersRoute,
  } as any)
const AuthenticatedUsernameCategoryRequestIdRoute =
  AuthenticatedUsernameCategoryRequestIdRouteImport.update({
    id: '/$username/category-request/$id',
    path: '/$username/category-request/$id',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedUsernameUpdateNewsIdEditRoute =
  AuthenticatedUsernameUpdateNewsIdEditRouteImport.update({
    id: '/$id/edit',
    path: '/$id/edit',
    getParentRoute: () => AuthenticatedUsernameUpdateNewsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/app': typeof AppRoute
  '/book': typeof BookRoute
  '/insights': typeof InsightsRoute
  '/login': typeof LoginRoute
  '/news': typeof NewsRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/services': typeof ServicesRouteWithChildren
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/$username/book': typeof UsernameBookRoute
  '/admin/login': typeof AdminLoginRoute
  '/dashboard/admin': typeof DashboardAdminRoute
  '/dashboard/homeowner': typeof DashboardHomeownerRoute
  '/dashboard/provider': typeof DashboardProviderRoute
  '/news/$id': typeof NewsIdRoute
  '/services/$serviceId': typeof ServicesServiceIdRouteWithChildren
  '/news/': typeof NewsIndexRoute
  '/services/': typeof ServicesIndexRoute
  '/$username/active-bookings': typeof AuthenticatedUsernameActiveBookingsRoute
  '/$username/dashboard': typeof AuthenticatedUsernameDashboardRoute
  '/$username/homeowners': typeof AuthenticatedUsernameHomeownersRouteWithChildren
  '/$username/jobs': typeof AuthenticatedUsernameJobsRoute
  '/$username/jobs-bookings': typeof AuthenticatedUsernameJobsBookingsRoute
  '/$username/myservices': typeof AuthenticatedUsernameMyservicesRouteWithChildren
  '/$username/new-jobs': typeof AuthenticatedUsernameNewJobsRoute
  '/$username/notification': typeof AuthenticatedUsernameNotificationRoute
  '/$username/overview': typeof AuthenticatedUsernameOverviewRoute
  '/$username/past-bookings': typeof AuthenticatedUsernamePastBookingsRoute
  '/$username/profile': typeof AuthenticatedUsernameProfileRoute
  '/$username/providers': typeof AuthenticatedUsernameProvidersRouteWithChildren
  '/$username/reviews': typeof AuthenticatedUsernameReviewsRoute
  '/$username/security': typeof AuthenticatedUsernameSecurityRoute
  '/$username/system-health': typeof AuthenticatedUsernameSystemHealthRoute
  '/$username/update-news': typeof AuthenticatedUsernameUpdateNewsRouteWithChildren
  '/$username/wallet': typeof AuthenticatedUsernameWalletRoute
  '/services/$serviceId/$subServiceId': typeof ServicesServiceIdSubServiceIdRoute
  '/services/$serviceId/': typeof ServicesServiceIdIndexRoute
  '/$username/category-request/$id': typeof AuthenticatedUsernameCategoryRequestIdRoute
  '/$username/homeowners/$id': typeof AuthenticatedUsernameHomeownersIdRoute
  '/$username/myservices/$cardId': typeof AuthenticatedUsernameMyservicesCardIdRoute
  '/$username/myservices/new': typeof AuthenticatedUsernameMyservicesNewRoute
  '/$username/provider-request/$id': typeof AuthenticatedUsernameProviderRequestIdRoute
  '/$username/providers/$id': typeof AuthenticatedUsernameProvidersIdRoute
  '/$username/update-news/new': typeof AuthenticatedUsernameUpdateNewsNewRoute
  '/$username/category-request/': typeof AuthenticatedUsernameCategoryRequestIndexRoute
  '/$username/homeowners/': typeof AuthenticatedUsernameHomeownersIndexRoute
  '/$username/myservices/': typeof AuthenticatedUsernameMyservicesIndexRoute
  '/$username/provider-request/': typeof AuthenticatedUsernameProviderRequestIndexRoute
  '/$username/providers/': typeof AuthenticatedUsernameProvidersIndexRoute
  '/$username/update-news/': typeof AuthenticatedUsernameUpdateNewsIndexRoute
  '/$username/update-news/$id/edit': typeof AuthenticatedUsernameUpdateNewsIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/app': typeof AppRoute
  '/book': typeof BookRoute
  '/insights': typeof InsightsRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/$username/book': typeof UsernameBookRoute
  '/admin/login': typeof AdminLoginRoute
  '/dashboard/admin': typeof DashboardAdminRoute
  '/dashboard/homeowner': typeof DashboardHomeownerRoute
  '/dashboard/provider': typeof DashboardProviderRoute
  '/news/$id': typeof NewsIdRoute
  '/news': typeof NewsIndexRoute
  '/services': typeof ServicesIndexRoute
  '/$username/active-bookings': typeof AuthenticatedUsernameActiveBookingsRoute
  '/$username/dashboard': typeof AuthenticatedUsernameDashboardRoute
  '/$username/jobs': typeof AuthenticatedUsernameJobsRoute
  '/$username/jobs-bookings': typeof AuthenticatedUsernameJobsBookingsRoute
  '/$username/new-jobs': typeof AuthenticatedUsernameNewJobsRoute
  '/$username/notification': typeof AuthenticatedUsernameNotificationRoute
  '/$username/overview': typeof AuthenticatedUsernameOverviewRoute
  '/$username/past-bookings': typeof AuthenticatedUsernamePastBookingsRoute
  '/$username/profile': typeof AuthenticatedUsernameProfileRoute
  '/$username/reviews': typeof AuthenticatedUsernameReviewsRoute
  '/$username/security': typeof AuthenticatedUsernameSecurityRoute
  '/$username/system-health': typeof AuthenticatedUsernameSystemHealthRoute
  '/$username/wallet': typeof AuthenticatedUsernameWalletRoute
  '/services/$serviceId/$subServiceId': typeof ServicesServiceIdSubServiceIdRoute
  '/services/$serviceId': typeof ServicesServiceIdIndexRoute
  '/$username/category-request/$id': typeof AuthenticatedUsernameCategoryRequestIdRoute
  '/$username/homeowners/$id': typeof AuthenticatedUsernameHomeownersIdRoute
  '/$username/myservices/$cardId': typeof AuthenticatedUsernameMyservicesCardIdRoute
  '/$username/myservices/new': typeof AuthenticatedUsernameMyservicesNewRoute
  '/$username/provider-request/$id': typeof AuthenticatedUsernameProviderRequestIdRoute
  '/$username/providers/$id': typeof AuthenticatedUsernameProvidersIdRoute
  '/$username/update-news/new': typeof AuthenticatedUsernameUpdateNewsNewRoute
  '/$username/category-request': typeof AuthenticatedUsernameCategoryRequestIndexRoute
  '/$username/homeowners': typeof AuthenticatedUsernameHomeownersIndexRoute
  '/$username/myservices': typeof AuthenticatedUsernameMyservicesIndexRoute
  '/$username/provider-request': typeof AuthenticatedUsernameProviderRequestIndexRoute
  '/$username/providers': typeof AuthenticatedUsernameProvidersIndexRoute
  '/$username/update-news': typeof AuthenticatedUsernameUpdateNewsIndexRoute
  '/$username/update-news/$id/edit': typeof AuthenticatedUsernameUpdateNewsIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/about': typeof AboutRoute
  '/app': typeof AppRoute
  '/book': typeof BookRoute
  '/insights': typeof InsightsRoute
  '/login': typeof LoginRoute
  '/news': typeof NewsRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/services': typeof ServicesRouteWithChildren
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/$username/book': typeof UsernameBookRoute
  '/admin/login': typeof AdminLoginRoute
  '/dashboard/admin': typeof DashboardAdminRoute
  '/dashboard/homeowner': typeof DashboardHomeownerRoute
  '/dashboard/provider': typeof DashboardProviderRoute
  '/news/$id': typeof NewsIdRoute
  '/services/$serviceId': typeof ServicesServiceIdRouteWithChildren
  '/news/': typeof NewsIndexRoute
  '/services/': typeof ServicesIndexRoute
  '/_authenticated/$username/active-bookings': typeof AuthenticatedUsernameActiveBookingsRoute
  '/_authenticated/$username/dashboard': typeof AuthenticatedUsernameDashboardRoute
  '/_authenticated/$username/homeowners': typeof AuthenticatedUsernameHomeownersRouteWithChildren
  '/_authenticated/$username/jobs': typeof AuthenticatedUsernameJobsRoute
  '/_authenticated/$username/jobs-bookings': typeof AuthenticatedUsernameJobsBookingsRoute
  '/_authenticated/$username/myservices': typeof AuthenticatedUsernameMyservicesRouteWithChildren
  '/_authenticated/$username/new-jobs': typeof AuthenticatedUsernameNewJobsRoute
  '/_authenticated/$username/notification': typeof AuthenticatedUsernameNotificationRoute
  '/_authenticated/$username/overview': typeof AuthenticatedUsernameOverviewRoute
  '/_authenticated/$username/past-bookings': typeof AuthenticatedUsernamePastBookingsRoute
  '/_authenticated/$username/profile': typeof AuthenticatedUsernameProfileRoute
  '/_authenticated/$username/providers': typeof AuthenticatedUsernameProvidersRouteWithChildren
  '/_authenticated/$username/reviews': typeof AuthenticatedUsernameReviewsRoute
  '/_authenticated/$username/security': typeof AuthenticatedUsernameSecurityRoute
  '/_authenticated/$username/system-health': typeof AuthenticatedUsernameSystemHealthRoute
  '/_authenticated/$username/update-news': typeof AuthenticatedUsernameUpdateNewsRouteWithChildren
  '/_authenticated/$username/wallet': typeof AuthenticatedUsernameWalletRoute
  '/services/$serviceId/$subServiceId': typeof ServicesServiceIdSubServiceIdRoute
  '/services/$serviceId/': typeof ServicesServiceIdIndexRoute
  '/_authenticated/$username/category-request/$id': typeof AuthenticatedUsernameCategoryRequestIdRoute
  '/_authenticated/$username/homeowners/$id': typeof AuthenticatedUsernameHomeownersIdRoute
  '/_authenticated/$username/myservices/$cardId': typeof AuthenticatedUsernameMyservicesCardIdRoute
  '/_authenticated/$username/myservices/new': typeof AuthenticatedUsernameMyservicesNewRoute
  '/_authenticated/$username/provider-request/$id': typeof AuthenticatedUsernameProviderRequestIdRoute
  '/_authenticated/$username/providers/$id': typeof AuthenticatedUsernameProvidersIdRoute
  '/_authenticated/$username/update-news/new': typeof AuthenticatedUsernameUpdateNewsNewRoute
  '/_authenticated/$username/category-request/': typeof AuthenticatedUsernameCategoryRequestIndexRoute
  '/_authenticated/$username/homeowners/': typeof AuthenticatedUsernameHomeownersIndexRoute
  '/_authenticated/$username/myservices/': typeof AuthenticatedUsernameMyservicesIndexRoute
  '/_authenticated/$username/provider-request/': typeof AuthenticatedUsernameProviderRequestIndexRoute
  '/_authenticated/$username/providers/': typeof AuthenticatedUsernameProvidersIndexRoute
  '/_authenticated/$username/update-news/': typeof AuthenticatedUsernameUpdateNewsIndexRoute
  '/_authenticated/$username/update-news/$id/edit': typeof AuthenticatedUsernameUpdateNewsIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/app'
    | '/book'
    | '/insights'
    | '/login'
    | '/news'
    | '/privacy'
    | '/profile'
    | '/services'
    | '/settings'
    | '/signup'
    | '/terms'
    | '/$username/book'
    | '/admin/login'
    | '/dashboard/admin'
    | '/dashboard/homeowner'
    | '/dashboard/provider'
    | '/news/$id'
    | '/services/$serviceId'
    | '/news/'
    | '/services/'
    | '/$username/active-bookings'
    | '/$username/dashboard'
    | '/$username/homeowners'
    | '/$username/jobs'
    | '/$username/jobs-bookings'
    | '/$username/myservices'
    | '/$username/new-jobs'
    | '/$username/notification'
    | '/$username/overview'
    | '/$username/past-bookings'
    | '/$username/profile'
    | '/$username/providers'
    | '/$username/reviews'
    | '/$username/security'
    | '/$username/system-health'
    | '/$username/update-news'
    | '/$username/wallet'
    | '/services/$serviceId/$subServiceId'
    | '/services/$serviceId/'
    | '/$username/category-request/$id'
    | '/$username/homeowners/$id'
    | '/$username/myservices/$cardId'
    | '/$username/myservices/new'
    | '/$username/provider-request/$id'
    | '/$username/providers/$id'
    | '/$username/update-news/new'
    | '/$username/category-request/'
    | '/$username/homeowners/'
    | '/$username/myservices/'
    | '/$username/provider-request/'
    | '/$username/providers/'
    | '/$username/update-news/'
    | '/$username/update-news/$id/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/app'
    | '/book'
    | '/insights'
    | '/login'
    | '/privacy'
    | '/profile'
    | '/settings'
    | '/signup'
    | '/terms'
    | '/$username/book'
    | '/admin/login'
    | '/dashboard/admin'
    | '/dashboard/homeowner'
    | '/dashboard/provider'
    | '/news/$id'
    | '/news'
    | '/services'
    | '/$username/active-bookings'
    | '/$username/dashboard'
    | '/$username/jobs'
    | '/$username/jobs-bookings'
    | '/$username/new-jobs'
    | '/$username/notification'
    | '/$username/overview'
    | '/$username/past-bookings'
    | '/$username/profile'
    | '/$username/reviews'
    | '/$username/security'
    | '/$username/system-health'
    | '/$username/wallet'
    | '/services/$serviceId/$subServiceId'
    | '/services/$serviceId'
    | '/$username/category-request/$id'
    | '/$username/homeowners/$id'
    | '/$username/myservices/$cardId'
    | '/$username/myservices/new'
    | '/$username/provider-request/$id'
    | '/$username/providers/$id'
    | '/$username/update-news/new'
    | '/$username/category-request'
    | '/$username/homeowners'
    | '/$username/myservices'
    | '/$username/provider-request'
    | '/$username/providers'
    | '/$username/update-news'
    | '/$username/update-news/$id/edit'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/app'
    | '/book'
    | '/insights'
    | '/login'
    | '/news'
    | '/privacy'
    | '/profile'
    | '/services'
    | '/settings'
    | '/signup'
    | '/terms'
    | '/$username/book'
    | '/admin/login'
    | '/dashboard/admin'
    | '/dashboard/homeowner'
    | '/dashboard/provider'
    | '/news/$id'
    | '/services/$serviceId'
    | '/news/'
    | '/services/'
    | '/_authenticated/$username/active-bookings'
    | '/_authenticated/$username/dashboard'
    | '/_authenticated/$username/homeowners'
    | '/_authenticated/$username/jobs'
    | '/_authenticated/$username/jobs-bookings'
    | '/_authenticated/$username/myservices'
    | '/_authenticated/$username/new-jobs'
    | '/_authenticated/$username/notification'
    | '/_authenticated/$username/overview'
    | '/_authenticated/$username/past-bookings'
    | '/_authenticated/$username/profile'
    | '/_authenticated/$username/providers'
    | '/_authenticated/$username/reviews'
    | '/_authenticated/$username/security'
    | '/_authenticated/$username/system-health'
    | '/_authenticated/$username/update-news'
    | '/_authenticated/$username/wallet'
    | '/services/$serviceId/$subServiceId'
    | '/services/$serviceId/'
    | '/_authenticated/$username/category-request/$id'
    | '/_authenticated/$username/homeowners/$id'
    | '/_authenticated/$username/myservices/$cardId'
    | '/_authenticated/$username/myservices/new'
    | '/_authenticated/$username/provider-request/$id'
    | '/_authenticated/$username/providers/$id'
    | '/_authenticated/$username/update-news/new'
    | '/_authenticated/$username/category-request/'
    | '/_authenticated/$username/homeowners/'
    | '/_authenticated/$username/myservices/'
    | '/_authenticated/$username/provider-request/'
    | '/_authenticated/$username/providers/'
    | '/_authenticated/$username/update-news/'
    | '/_authenticated/$username/update-news/$id/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AboutRoute: typeof AboutRoute
  AppRoute: typeof AppRoute
  BookRoute: typeof BookRoute
  InsightsRoute: typeof InsightsRoute
  LoginRoute: typeof LoginRoute
  NewsRoute: typeof NewsRouteWithChildren
  PrivacyRoute: typeof PrivacyRoute
  ProfileRoute: typeof ProfileRoute
  ServicesRoute: typeof ServicesRouteWithChildren
  SettingsRoute: typeof SettingsRoute
  SignupRoute: typeof SignupRoute
  TermsRoute: typeof TermsRoute
  UsernameBookRoute: typeof UsernameBookRoute
  AdminLoginRoute: typeof AdminLoginRoute
  DashboardAdminRoute: typeof DashboardAdminRoute
  DashboardHomeownerRoute: typeof DashboardHomeownerRoute
  DashboardProviderRoute: typeof DashboardProviderRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news': {
      id: '/news'
      path: '/news'
      fullPath: '/news'
      preLoaderRoute: typeof NewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insights': {
      id: '/insights'
      path: '/insights'
      fullPath: '/insights'
      preLoaderRoute: typeof InsightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book': {
      id: '/book'
      path: '/book'
      fullPath: '/book'
      preLoaderRoute: typeof BookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/': {
      id: '/services/'
      path: '/'
      fullPath: '/services/'
      preLoaderRoute: typeof ServicesIndexRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/news/': {
      id: '/news/'
      path: '/'
      fullPath: '/news/'
      preLoaderRoute: typeof NewsIndexRouteImport
      parentRoute: typeof NewsRoute
    }
    '/services/$serviceId': {
      id: '/services/$serviceId'
      path: '/$serviceId'
      fullPath: '/services/$serviceId'
      preLoaderRoute: typeof ServicesServiceIdRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/news/$id': {
      id: '/news/$id'
      path: '/$id'
      fullPath: '/news/$id'
      preLoaderRoute: typeof NewsIdRouteImport
      parentRoute: typeof NewsRoute
    }
    '/dashboard/provider': {
      id: '/dashboard/provider'
      path: '/dashboard/provider'
      fullPath: '/dashboard/provider'
      preLoaderRoute: typeof DashboardProviderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/homeowner': {
      id: '/dashboard/homeowner'
      path: '/dashboard/homeowner'
      fullPath: '/dashboard/homeowner'
      preLoaderRoute: typeof DashboardHomeownerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/admin': {
      id: '/dashboard/admin'
      path: '/dashboard/admin'
      fullPath: '/dashboard/admin'
      preLoaderRoute: typeof DashboardAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$username/book': {
      id: '/$username/book'
      path: '/$username/book'
      fullPath: '/$username/book'
      preLoaderRoute: typeof UsernameBookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/$serviceId/': {
      id: '/services/$serviceId/'
      path: '/'
      fullPath: '/services/$serviceId/'
      preLoaderRoute: typeof ServicesServiceIdIndexRouteImport
      parentRoute: typeof ServicesServiceIdRoute
    }
    '/services/$serviceId/$subServiceId': {
      id: '/services/$serviceId/$subServiceId'
      path: '/$subServiceId'
      fullPath: '/services/$serviceId/$subServiceId'
      preLoaderRoute: typeof ServicesServiceIdSubServiceIdRouteImport
      parentRoute: typeof ServicesServiceIdRoute
    }
    '/_authenticated/$username/wallet': {
      id: '/_authenticated/$username/wallet'
      path: '/$username/wallet'
      fullPath: '/$username/wallet'
      preLoaderRoute: typeof AuthenticatedUsernameWalletRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/$username/update-news': {
      id: '/_authenticated/$username/update-news'
      path: '/$username/update-news'
      fullPath: '/$username/update-news'
      preLoaderRoute: typeof AuthenticatedUsernameUpdateNewsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/$username/system-health': {
      id: '/_authenticated/$username/system-health'
      path: '/$username/system-health'
      fullPath: '/$username/system-health'
      preLoaderRoute: typeof AuthenticatedUsernameSystemHealthRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/$username/security': {
      id: '/_authenticated/$username/security'
      path: '/$username/security'
      fullPath: '/$username/security'
      preLoaderRoute: typeof AuthenticatedUsernameSecurityRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/$username/reviews': {
      id: '/_authenticated/$username/reviews'
      path: '/$username/reviews'
      fullPath: '/$username/reviews'
      preLoaderRoute: typeof AuthenticatedUsernameReviewsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/$username/providers': {
      id: '/_authenticated/$username/providers'
      path: '/$username/providers'
      fullPath: '/$username/providers'
      preLoaderRoute: typeof AuthenticatedUsernameProvidersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/$username/profile': {
      id: '/_authenticated/$username/profile'
      path: '/$username/profile'
      fullPath: '/$username/profile'
      preLoaderRoute: typeof AuthenticatedUsernameProfileRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/$username/past-bookings': {
      id: '/_authenticated/$username/past-bookings'
      path: '/$username/past-bookings'
      fullPath: '/$username/past-bookings'
      preLoaderRoute: typeof AuthenticatedUsernamePastBookingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/$username/overview': {
      id: '/_authenticated/$username/overview'
      path: '/$username/overview'
      fullPath: '/$username/overview'
      preLoaderRoute: typeof AuthenticatedUsernameOverviewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/$username/notification': {
      id: '/_authenticated/$username/notification'
      path: '/$username/notification'
      fullPath: '/$username/notification'
      preLoaderRoute: typeof AuthenticatedUsernameNotificationRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/$username/new-jobs': {
      id: '/_authenticated/$username/new-jobs'
      path: '/$username/new-jobs'
      fullPath: '/$username/new-jobs'
      preLoaderRoute: typeof AuthenticatedUsernameNewJobsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/$username/myservices': {
      id: '/_authenticated/$username/myservices'
      path: '/$username/myservices'
      fullPath: '/$username/myservices'
      preLoaderRoute: typeof AuthenticatedUsernameMyservicesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/$username/jobs-bookings': {
      id: '/_authenticated/$username/jobs-bookings'
      path: '/$username/jobs-bookings'
      fullPath: '/$username/jobs-bookings'
      preLoaderRoute: typeof AuthenticatedUsernameJobsBookingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/$username/jobs': {
      id: '/_authenticated/$username/jobs'
      path: '/$username/jobs'
      fullPath: '/$username/jobs'
      preLoaderRoute: typeof AuthenticatedUsernameJobsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/$username/homeowners': {
      id: '/_authenticated/$username/homeowners'
      path: '/$username/homeowners'
      fullPath: '/$username/homeowners'
      preLoaderRoute: typeof AuthenticatedUsernameHomeownersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/$username/dashboard': {
      id: '/_authenticated/$username/dashboard'
      path: '/$username/dashboard'
      fullPath: '/$username/dashboard'
      preLoaderRoute: typeof AuthenticatedUsernameDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/$username/active-bookings': {
      id: '/_authenticated/$username/active-bookings'
      path: '/$username/active-bookings'
      fullPath: '/$username/active-bookings'
      preLoaderRoute: typeof AuthenticatedUsernameActiveBookingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/$username/update-news/': {
      id: '/_authenticated/$username/update-news/'
      path: '/'
      fullPath: '/$username/update-news/'
      preLoaderRoute: typeof AuthenticatedUsernameUpdateNewsIndexRouteImport
      parentRoute: typeof AuthenticatedUsernameUpdateNewsRoute
    }
    '/_authenticated/$username/providers/': {
      id: '/_authenticated/$username/providers/'
      path: '/'
      fullPath: '/$username/providers/'
      preLoaderRoute: typeof AuthenticatedUsernameProvidersIndexRouteImport
      parentRoute: typeof AuthenticatedUsernameProvidersRoute
    }
    '/_authenticated/$username/provider-request/': {
      id: '/_authenticated/$username/provider-request/'
      path: '/$username/provider-request'
      fullPath: '/$username/provider-request/'
      preLoaderRoute: typeof AuthenticatedUsernameProviderRequestIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/$username/myservices/': {
      id: '/_authenticated/$username/myservices/'
      path: '/'
      fullPath: '/$username/myservices/'
      preLoaderRoute: typeof AuthenticatedUsernameMyservicesIndexRouteImport
      parentRoute: typeof AuthenticatedUsernameMyservicesRoute
    }
    '/_authenticated/$username/homeowners/': {
      id: '/_authenticated/$username/homeowners/'
      path: '/'
      fullPath: '/$username/homeowners/'
      preLoaderRoute: typeof AuthenticatedUsernameHomeownersIndexRouteImport
      parentRoute: typeof AuthenticatedUsernameHomeownersRoute
    }
    '/_authenticated/$username/category-request/': {
      id: '/_authenticated/$username/category-request/'
      path: '/$username/category-request'
      fullPath: '/$username/category-request/'
      preLoaderRoute: typeof AuthenticatedUsernameCategoryRequestIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/$username/update-news/new': {
      id: '/_authenticated/$username/update-news/new'
      path: '/new'
      fullPath: '/$username/update-news/new'
      preLoaderRoute: typeof AuthenticatedUsernameUpdateNewsNewRouteImport
      parentRoute: typeof AuthenticatedUsernameUpdateNewsRoute
    }
    '/_authenticated/$username/providers/$id': {
      id: '/_authenticated/$username/providers/$id'
      path: '/$id'
      fullPath: '/$username/providers/$id'
      preLoaderRoute: typeof AuthenticatedUsernameProvidersIdRouteImport
      parentRoute: typeof AuthenticatedUsernameProvidersRoute
    }
    '/_authenticated/$username/provider-request/$id': {
      id: '/_authenticated/$username/provider-request/$id'
      path: '/$username/provider-request/$id'
      fullPath: '/$username/provider-request/$id'
      preLoaderRoute: typeof AuthenticatedUsernameProviderRequestIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/$username/myservices/new': {
      id: '/_authenticated/$username/myservices/new'
      path: '/new'
      fullPath: '/$username/myservices/new'
      preLoaderRoute: typeof AuthenticatedUsernameMyservicesNewRouteImport
      parentRoute: typeof AuthenticatedUsernameMyservicesRoute
    }
    '/_authenticated/$username/myservices/$cardId': {
      id: '/_authenticated/$username/myservices/$cardId'
      path: '/$cardId'
      fullPath: '/$username/myservices/$cardId'
      preLoaderRoute: typeof AuthenticatedUsernameMyservicesCardIdRouteImport
      parentRoute: typeof AuthenticatedUsernameMyservicesRoute
    }
    '/_authenticated/$username/homeowners/$id': {
      id: '/_authenticated/$username/homeowners/$id'
      path: '/$id'
      fullPath: '/$username/homeowners/$id'
      preLoaderRoute: typeof AuthenticatedUsernameHomeownersIdRouteImport
      parentRoute: typeof AuthenticatedUsernameHomeownersRoute
    }
    '/_authenticated/$username/category-request/$id': {
      id: '/_authenticated/$username/category-request/$id'
      path: '/$username/category-request/$id'
      fullPath: '/$username/category-request/$id'
      preLoaderRoute: typeof AuthenticatedUsernameCategoryRequestIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/$username/update-news/$id/edit': {
      id: '/_authenticated/$username/update-news/$id/edit'
      path: '/$id/edit'
      fullPath: '/$username/update-news/$id/edit'
      preLoaderRoute: typeof AuthenticatedUsernameUpdateNewsIdEditRouteImport
      parentRoute: typeof AuthenticatedUsernameUpdateNewsRoute
    }
  }
}

interface AuthenticatedUsernameHomeownersRouteChildren {
  AuthenticatedUsernameHomeownersIdRoute: typeof AuthenticatedUsernameHomeownersIdRoute
  AuthenticatedUsernameHomeownersIndexRoute: typeof AuthenticatedUsernameHomeownersIndexRoute
}

const AuthenticatedUsernameHomeownersRouteChildren: AuthenticatedUsernameHomeownersRouteChildren =
  {
    AuthenticatedUsernameHomeownersIdRoute:
      AuthenticatedUsernameHomeownersIdRoute,
    AuthenticatedUsernameHomeownersIndexRoute:
      AuthenticatedUsernameHomeownersIndexRoute,
  }

const AuthenticatedUsernameHomeownersRouteWithChildren =
  AuthenticatedUsernameHomeownersRoute._addFileChildren(
    AuthenticatedUsernameHomeownersRouteChildren,
  )

interface AuthenticatedUsernameMyservicesRouteChildren {
  AuthenticatedUsernameMyservicesCardIdRoute: typeof AuthenticatedUsernameMyservicesCardIdRoute
  AuthenticatedUsernameMyservicesNewRoute: typeof AuthenticatedUsernameMyservicesNewRoute
  AuthenticatedUsernameMyservicesIndexRoute: typeof AuthenticatedUsernameMyservicesIndexRoute
}

const AuthenticatedUsernameMyservicesRouteChildren: AuthenticatedUsernameMyservicesRouteChildren =
  {
    AuthenticatedUsernameMyservicesCardIdRoute:
      AuthenticatedUsernameMyservicesCardIdRoute,
    AuthenticatedUsernameMyservicesNewRoute:
      AuthenticatedUsernameMyservicesNewRoute,
    AuthenticatedUsernameMyservicesIndexRoute:
      AuthenticatedUsernameMyservicesIndexRoute,
  }

const AuthenticatedUsernameMyservicesRouteWithChildren =
  AuthenticatedUsernameMyservicesRoute._addFileChildren(
    AuthenticatedUsernameMyservicesRouteChildren,
  )

interface AuthenticatedUsernameProvidersRouteChildren {
  AuthenticatedUsernameProvidersIdRoute: typeof AuthenticatedUsernameProvidersIdRoute
  AuthenticatedUsernameProvidersIndexRoute: typeof AuthenticatedUsernameProvidersIndexRoute
}

const AuthenticatedUsernameProvidersRouteChildren: AuthenticatedUsernameProvidersRouteChildren =
  {
    AuthenticatedUsernameProvidersIdRoute:
      AuthenticatedUsernameProvidersIdRoute,
    AuthenticatedUsernameProvidersIndexRoute:
      AuthenticatedUsernameProvidersIndexRoute,
  }

const AuthenticatedUsernameProvidersRouteWithChildren =
  AuthenticatedUsernameProvidersRoute._addFileChildren(
    AuthenticatedUsernameProvidersRouteChildren,
  )

interface AuthenticatedUsernameUpdateNewsRouteChildren {
  AuthenticatedUsernameUpdateNewsNewRoute: typeof AuthenticatedUsernameUpdateNewsNewRoute
  AuthenticatedUsernameUpdateNewsIndexRoute: typeof AuthenticatedUsernameUpdateNewsIndexRoute
  AuthenticatedUsernameUpdateNewsIdEditRoute: typeof AuthenticatedUsernameUpdateNewsIdEditRoute
}

const AuthenticatedUsernameUpdateNewsRouteChildren: AuthenticatedUsernameUpdateNewsRouteChildren =
  {
    AuthenticatedUsernameUpdateNewsNewRoute:
      AuthenticatedUsernameUpdateNewsNewRoute,
    AuthenticatedUsernameUpdateNewsIndexRoute:
      AuthenticatedUsernameUpdateNewsIndexRoute,
    AuthenticatedUsernameUpdateNewsIdEditRoute:
      AuthenticatedUsernameUpdateNewsIdEditRoute,
  }

const AuthenticatedUsernameUpdateNewsRouteWithChildren =
  AuthenticatedUsernameUpdateNewsRoute._addFileChildren(
    AuthenticatedUsernameUpdateNewsRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedUsernameActiveBookingsRoute: typeof AuthenticatedUsernameActiveBookingsRoute
  AuthenticatedUsernameDashboardRoute: typeof AuthenticatedUsernameDashboardRoute
  AuthenticatedUsernameHomeownersRoute: typeof AuthenticatedUsernameHomeownersRouteWithChildren
  AuthenticatedUsernameJobsRoute: typeof AuthenticatedUsernameJobsRoute
  AuthenticatedUsernameJobsBookingsRoute: typeof AuthenticatedUsernameJobsBookingsRoute
  AuthenticatedUsernameMyservicesRoute: typeof AuthenticatedUsernameMyservicesRouteWithChildren
  AuthenticatedUsernameNewJobsRoute: typeof AuthenticatedUsernameNewJobsRoute
  AuthenticatedUsernameNotificationRoute: typeof AuthenticatedUsernameNotificationRoute
  AuthenticatedUsernameOverviewRoute: typeof AuthenticatedUsernameOverviewRoute
  AuthenticatedUsernamePastBookingsRoute: typeof AuthenticatedUsernamePastBookingsRoute
  AuthenticatedUsernameProfileRoute: typeof AuthenticatedUsernameProfileRoute
  AuthenticatedUsernameProvidersRoute: typeof AuthenticatedUsernameProvidersRouteWithChildren
  AuthenticatedUsernameReviewsRoute: typeof AuthenticatedUsernameReviewsRoute
  AuthenticatedUsernameSecurityRoute: typeof AuthenticatedUsernameSecurityRoute
  AuthenticatedUsernameSystemHealthRoute: typeof AuthenticatedUsernameSystemHealthRoute
  AuthenticatedUsernameUpdateNewsRoute: typeof AuthenticatedUsernameUpdateNewsRouteWithChildren
  AuthenticatedUsernameWalletRoute: typeof AuthenticatedUsernameWalletRoute
  AuthenticatedUsernameCategoryRequestIdRoute: typeof AuthenticatedUsernameCategoryRequestIdRoute
  AuthenticatedUsernameProviderRequestIdRoute: typeof AuthenticatedUsernameProviderRequestIdRoute
  AuthenticatedUsernameCategoryRequestIndexRoute: typeof AuthenticatedUsernameCategoryRequestIndexRoute
  AuthenticatedUsernameProviderRequestIndexRoute: typeof AuthenticatedUsernameProviderRequestIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedUsernameActiveBookingsRoute:
    AuthenticatedUsernameActiveBookingsRoute,
  AuthenticatedUsernameDashboardRoute: AuthenticatedUsernameDashboardRoute,
  AuthenticatedUsernameHomeownersRoute:
    AuthenticatedUsernameHomeownersRouteWithChildren,
  AuthenticatedUsernameJobsRoute: AuthenticatedUsernameJobsRoute,
  AuthenticatedUsernameJobsBookingsRoute:
    AuthenticatedUsernameJobsBookingsRoute,
  AuthenticatedUsernameMyservicesRoute:
    AuthenticatedUsernameMyservicesRouteWithChildren,
  AuthenticatedUsernameNewJobsRoute: AuthenticatedUsernameNewJobsRoute,
  AuthenticatedUsernameNotificationRoute:
    AuthenticatedUsernameNotificationRoute,
  AuthenticatedUsernameOverviewRoute: AuthenticatedUsernameOverviewRoute,
  AuthenticatedUsernamePastBookingsRoute:
    AuthenticatedUsernamePastBookingsRoute,
  AuthenticatedUsernameProfileRoute: AuthenticatedUsernameProfileRoute,
  AuthenticatedUsernameProvidersRoute:
    AuthenticatedUsernameProvidersRouteWithChildren,
  AuthenticatedUsernameReviewsRoute: AuthenticatedUsernameReviewsRoute,
  AuthenticatedUsernameSecurityRoute: AuthenticatedUsernameSecurityRoute,
  AuthenticatedUsernameSystemHealthRoute:
    AuthenticatedUsernameSystemHealthRoute,
  AuthenticatedUsernameUpdateNewsRoute:
    AuthenticatedUsernameUpdateNewsRouteWithChildren,
  AuthenticatedUsernameWalletRoute: AuthenticatedUsernameWalletRoute,
  AuthenticatedUsernameCategoryRequestIdRoute:
    AuthenticatedUsernameCategoryRequestIdRoute,
  AuthenticatedUsernameProviderRequestIdRoute:
    AuthenticatedUsernameProviderRequestIdRoute,
  AuthenticatedUsernameCategoryRequestIndexRoute:
    AuthenticatedUsernameCategoryRequestIndexRoute,
  AuthenticatedUsernameProviderRequestIndexRoute:
    AuthenticatedUsernameProviderRequestIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface NewsRouteChildren {
  NewsIdRoute: typeof NewsIdRoute
  NewsIndexRoute: typeof NewsIndexRoute
}

const NewsRouteChildren: NewsRouteChildren = {
  NewsIdRoute: NewsIdRoute,
  NewsIndexRoute: NewsIndexRoute,
}

const NewsRouteWithChildren = NewsRoute._addFileChildren(NewsRouteChildren)

interface ServicesServiceIdRouteChildren {
  ServicesServiceIdSubServiceIdRoute: typeof ServicesServiceIdSubServiceIdRoute
  ServicesServiceIdIndexRoute: typeof ServicesServiceIdIndexRoute
}

const ServicesServiceIdRouteChildren: ServicesServiceIdRouteChildren = {
  ServicesServiceIdSubServiceIdRoute: ServicesServiceIdSubServiceIdRoute,
  ServicesServiceIdIndexRoute: ServicesServiceIdIndexRoute,
}

const ServicesServiceIdRouteWithChildren =
  ServicesServiceIdRoute._addFileChildren(ServicesServiceIdRouteChildren)

interface ServicesRouteChildren {
  ServicesServiceIdRoute: typeof ServicesServiceIdRouteWithChildren
  ServicesIndexRoute: typeof ServicesIndexRoute
}

const ServicesRouteChildren: ServicesRouteChildren = {
  ServicesServiceIdRoute: ServicesServiceIdRouteWithChildren,
  ServicesIndexRoute: ServicesIndexRoute,
}

const ServicesRouteWithChildren = ServicesRoute._addFileChildren(
  ServicesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AboutRoute: AboutRoute,
  AppRoute: AppRoute,
  BookRoute: BookRoute,
  InsightsRoute: InsightsRoute,
  LoginRoute: LoginRoute,
  NewsRoute: NewsRouteWithChildren,
  PrivacyRoute: PrivacyRoute,
  ProfileRoute: ProfileRoute,
  ServicesRoute: ServicesRouteWithChildren,
  SettingsRoute: SettingsRoute,
  SignupRoute: SignupRoute,
  TermsRoute: TermsRoute,
  UsernameBookRoute: UsernameBookRoute,
  AdminLoginRoute: AdminLoginRoute,
  DashboardAdminRoute: DashboardAdminRoute,
  DashboardHomeownerRoute: DashboardHomeownerRoute,
  DashboardProviderRoute: DashboardProviderRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
